/*
 * This file is generated by jOOQ.
*/
package io.vilya.eurus.core.entity;


import javax.annotation.Generated;

import io.vilya.eurus.core.entity.tables.Account;
import io.vilya.eurus.core.entity.tables.AccountRMember;
import io.vilya.eurus.core.entity.tables.AccountRRole;
import io.vilya.eurus.core.entity.tables.Member;
import io.vilya.eurus.core.entity.tables.Perm;
import io.vilya.eurus.core.entity.tables.PermRRole;
import io.vilya.eurus.core.entity.tables.Role;


/**
 * Convenience access to all tables in DB_VY_CORE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_VY_CORE.account</code>.
     */
    public static final Account ACCOUNT = io.vilya.eurus.core.entity.tables.Account.ACCOUNT;

    /**
     * The table <code>DB_VY_CORE.account_r_member</code>.
     */
    public static final AccountRMember ACCOUNT_R_MEMBER = io.vilya.eurus.core.entity.tables.AccountRMember.ACCOUNT_R_MEMBER;

    /**
     * The table <code>DB_VY_CORE.account_r_role</code>.
     */
    public static final AccountRRole ACCOUNT_R_ROLE = io.vilya.eurus.core.entity.tables.AccountRRole.ACCOUNT_R_ROLE;

    /**
     * The table <code>DB_VY_CORE.member</code>.
     */
    public static final Member MEMBER = io.vilya.eurus.core.entity.tables.Member.MEMBER;

    /**
     * The table <code>DB_VY_CORE.perm</code>.
     */
    public static final Perm PERM = io.vilya.eurus.core.entity.tables.Perm.PERM;

    /**
     * The table <code>DB_VY_CORE.perm_r_role</code>.
     */
    public static final PermRRole PERM_R_ROLE = io.vilya.eurus.core.entity.tables.PermRRole.PERM_R_ROLE;

    /**
     * The table <code>DB_VY_CORE.role</code>.
     */
    public static final Role ROLE = io.vilya.eurus.core.entity.tables.Role.ROLE;
}
