/*
 * This file is generated by jOOQ.
*/
package io.vilya.eurus.core.entity.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import io.vilya.eurus.core.entity.tables.AccountRMember;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRMemberRecord extends UpdatableRecordImpl<AccountRMemberRecord> implements Record6<Integer, Integer, Integer, Date, Date, Boolean> {

    private static final long serialVersionUID = 1451745572;

    /**
     * Setter for <code>DB_VY_CORE.account_r_member.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.account_r_member.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DB_VY_CORE.account_r_member.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.account_r_member.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DB_VY_CORE.account_r_member.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.account_r_member.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DB_VY_CORE.account_r_member.create_time</code>.
     */
    public void setCreateTime(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.account_r_member.create_time</code>.
     */
    public Date getCreateTime() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>DB_VY_CORE.account_r_member.update_time</code>.
     */
    public void setUpdateTime(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.account_r_member.update_time</code>.
     */
    public Date getUpdateTime() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>DB_VY_CORE.account_r_member.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.account_r_member.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Date, Date, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Date, Date, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AccountRMember.ACCOUNT_R_MEMBER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AccountRMember.ACCOUNT_R_MEMBER.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AccountRMember.ACCOUNT_R_MEMBER.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return AccountRMember.ACCOUNT_R_MEMBER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return AccountRMember.ACCOUNT_R_MEMBER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return AccountRMember.ACCOUNT_R_MEMBER.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRMemberRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRMemberRecord value2(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRMemberRecord value3(Integer value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRMemberRecord value4(Date value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRMemberRecord value5(Date value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRMemberRecord value6(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRMemberRecord values(Integer value1, Integer value2, Integer value3, Date value4, Date value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRMemberRecord
     */
    public AccountRMemberRecord() {
        super(AccountRMember.ACCOUNT_R_MEMBER);
    }

    /**
     * Create a detached, initialised AccountRMemberRecord
     */
    public AccountRMemberRecord(Integer id, Integer accountId, Integer memberId, Date createTime, Date updateTime, Boolean isDeleted) {
        super(AccountRMember.ACCOUNT_R_MEMBER);

        set(0, id);
        set(1, accountId);
        set(2, memberId);
        set(3, createTime);
        set(4, updateTime);
        set(5, isDeleted);
    }
}
