/*
 * This file is generated by jOOQ.
*/
package io.vilya.eurus.core.entity.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import io.vilya.eurus.core.entity.tables.PermRRole;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermRRoleRecord extends UpdatableRecordImpl<PermRRoleRecord> implements Record6<Integer, Integer, Integer, Date, Date, Boolean> {

    private static final long serialVersionUID = 566259975;

    /**
     * Setter for <code>DB_VY_CORE.perm_r_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm_r_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm_r_role.perm_id</code>.
     */
    public void setPermId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm_r_role.perm_id</code>.
     */
    public Integer getPermId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm_r_role.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm_r_role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm_r_role.create_time</code>.
     */
    public void setCreateTime(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm_r_role.create_time</code>.
     */
    public Date getCreateTime() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm_r_role.update_time</code>.
     */
    public void setUpdateTime(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm_r_role.update_time</code>.
     */
    public Date getUpdateTime() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm_r_role.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm_r_role.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Date, Date, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Date, Date, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PermRRole.PERM_R_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PermRRole.PERM_R_ROLE.PERM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PermRRole.PERM_R_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return PermRRole.PERM_R_ROLE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return PermRRole.PERM_R_ROLE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return PermRRole.PERM_R_ROLE.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPermId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRRoleRecord value2(Integer value) {
        setPermId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRRoleRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRRoleRecord value4(Date value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRRoleRecord value5(Date value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRRoleRecord value6(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRRoleRecord values(Integer value1, Integer value2, Integer value3, Date value4, Date value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermRRoleRecord
     */
    public PermRRoleRecord() {
        super(PermRRole.PERM_R_ROLE);
    }

    /**
     * Create a detached, initialised PermRRoleRecord
     */
    public PermRRoleRecord(Integer id, Integer permId, Integer roleId, Date createTime, Date updateTime, Boolean isDeleted) {
        super(PermRRole.PERM_R_ROLE);

        set(0, id);
        set(1, permId);
        set(2, roleId);
        set(3, createTime);
        set(4, updateTime);
        set(5, isDeleted);
    }
}
