/*
 * This file is generated by jOOQ.
*/
package io.vilya.eurus.core.entity.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import io.vilya.eurus.core.entity.tables.Perm;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermRecord extends UpdatableRecordImpl<PermRecord> implements Record6<Integer, String, String, Date, Date, Boolean> {

    private static final long serialVersionUID = -1242684623;

    /**
     * Setter for <code>DB_VY_CORE.perm.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm.perm_name</code>.
     */
    public void setPermName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm.perm_name</code>.
     */
    public String getPermName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm.perm_desc</code>.
     */
    public void setPermDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm.perm_desc</code>.
     */
    public String getPermDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm.create_time</code>.
     */
    public void setCreateTime(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm.create_time</code>.
     */
    public Date getCreateTime() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm.update_time</code>.
     */
    public void setUpdateTime(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm.update_time</code>.
     */
    public Date getUpdateTime() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>DB_VY_CORE.perm.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB_VY_CORE.perm.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Date, Date, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Date, Date, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Perm.PERM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Perm.PERM.PERM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Perm.PERM.PERM_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Perm.PERM.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Perm.PERM.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Perm.PERM.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPermName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPermDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRecord value2(String value) {
        setPermName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRecord value3(String value) {
        setPermDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRecord value4(Date value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRecord value5(Date value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRecord value6(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermRecord values(Integer value1, String value2, String value3, Date value4, Date value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermRecord
     */
    public PermRecord() {
        super(Perm.PERM);
    }

    /**
     * Create a detached, initialised PermRecord
     */
    public PermRecord(Integer id, String permName, String permDesc, Date createTime, Date updateTime, Boolean isDeleted) {
        super(Perm.PERM);

        set(0, id);
        set(1, permName);
        set(2, permDesc);
        set(3, createTime);
        set(4, updateTime);
        set(5, isDeleted);
    }
}
