/*
 * This file is generated by jOOQ.
*/
package io.vilya.eurus.core.entity.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import io.vilya.eurus.core.entity.DbVyCore;
import io.vilya.eurus.core.entity.Keys;
import io.vilya.eurus.core.entity.tables.records.AccountRRoleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRRole extends TableImpl<AccountRRoleRecord> {

    private static final long serialVersionUID = -1275303305;

    /**
     * The reference instance of <code>DB_VY_CORE.account_r_role</code>
     */
    public static final AccountRRole ACCOUNT_R_ROLE = new AccountRRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRRoleRecord> getRecordType() {
        return AccountRRoleRecord.class;
    }

    /**
     * The column <code>DB_VY_CORE.account_r_role.id</code>.
     */
    public final TableField<AccountRRoleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.account_r_role.account_id</code>.
     */
    public final TableField<AccountRRoleRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.account_r_role.member_id</code>.
     */
    public final TableField<AccountRRoleRecord, Integer> MEMBER_ID = createField("member_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.account_r_role.create_time</code>.
     */
    public final TableField<AccountRRoleRecord, Date> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.account_r_role.update_time</code>.
     */
    public final TableField<AccountRRoleRecord, Date> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.account_r_role.is_deleted</code>.
     */
    public final TableField<AccountRRoleRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>DB_VY_CORE.account_r_role</code> table reference
     */
    public AccountRRole() {
        this("account_r_role", null);
    }

    /**
     * Create an aliased <code>DB_VY_CORE.account_r_role</code> table reference
     */
    public AccountRRole(String alias) {
        this(alias, ACCOUNT_R_ROLE);
    }

    private AccountRRole(String alias, Table<AccountRRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountRRole(String alias, Table<AccountRRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbVyCore.DB_VY_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccountRRoleRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_R_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccountRRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountRRoleRecord>>asList(Keys.KEY_ACCOUNT_R_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRRole as(String alias) {
        return new AccountRRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRRole rename(String name) {
        return new AccountRRole(name, null);
    }
}
