/*
 * This file is generated by jOOQ.
*/
package io.vilya.eurus.core.entity.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import io.vilya.eurus.core.entity.DbVyCore;
import io.vilya.eurus.core.entity.Keys;
import io.vilya.eurus.core.entity.tables.records.AccountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account extends TableImpl<AccountRecord> {

    private static final long serialVersionUID = 1025286538;

    /**
     * The reference instance of <code>DB_VY_CORE.account</code>
     */
    public static final Account ACCOUNT = new Account();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRecord> getRecordType() {
        return AccountRecord.class;
    }

    /**
     * The column <code>DB_VY_CORE.account.id</code>.
     */
    public final TableField<AccountRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.account.acc_username</code>. 用户名
     */
    public final TableField<AccountRecord, String> ACC_USERNAME = createField("acc_username", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "用户名");

    /**
     * The column <code>DB_VY_CORE.account.acc_password</code>. 密码
     */
    public final TableField<AccountRecord, String> ACC_PASSWORD = createField("acc_password", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "密码");

    /**
     * The column <code>DB_VY_CORE.account.token</code>.
     */
    public final TableField<AccountRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>DB_VY_CORE.account.create_time</code>. 记录创建时间
     */
    public final TableField<AccountRecord, Date> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "记录创建时间");

    /**
     * The column <code>DB_VY_CORE.account.update_time</code>. 记录更新时间
     */
    public final TableField<AccountRecord, Date> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "记录更新时间");

    /**
     * The column <code>DB_VY_CORE.account.is_deleted</code>. 记录是否被删除：0-否 1-是
     */
    public final TableField<AccountRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "记录是否被删除：0-否 1-是");

    /**
     * Create a <code>DB_VY_CORE.account</code> table reference
     */
    public Account() {
        this("account", null);
    }

    /**
     * Create an aliased <code>DB_VY_CORE.account</code> table reference
     */
    public Account(String alias) {
        this(alias, ACCOUNT);
    }

    private Account(String alias, Table<AccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private Account(String alias, Table<AccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbVyCore.DB_VY_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AccountRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccountRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccountRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountRecord>>asList(Keys.KEY_ACCOUNT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Account as(String alias) {
        return new Account(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Account rename(String name) {
        return new Account(name, null);
    }
}
