/*
 * This file is generated by jOOQ.
*/
package io.vilya.eurus.core.entity.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import io.vilya.eurus.core.entity.DbVyCore;
import io.vilya.eurus.core.entity.Keys;
import io.vilya.eurus.core.entity.tables.records.MemberRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Member extends TableImpl<MemberRecord> {

    private static final long serialVersionUID = 1568987852;

    /**
     * The reference instance of <code>DB_VY_CORE.member</code>
     */
    public static final Member MEMBER = new Member();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MemberRecord> getRecordType() {
        return MemberRecord.class;
    }

    /**
     * The column <code>DB_VY_CORE.member.id</code>.
     */
    public final TableField<MemberRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.member.mem_name</code>.
     */
    public final TableField<MemberRecord, String> MEM_NAME = createField("mem_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.member.mem_sex</code>.
     */
    public final TableField<MemberRecord, Byte> MEM_SEX = createField("mem_sex", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.member.mem_birth</code>.
     */
    public final TableField<MemberRecord, Date> MEM_BIRTH = createField("mem_birth", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.member.mem_mobile</code>.
     */
    public final TableField<MemberRecord, String> MEM_MOBILE = createField("mem_mobile", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>DB_VY_CORE.member.create_time</code>.
     */
    public final TableField<MemberRecord, Date> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>DB_VY_CORE.member.update_time</code>.
     */
    public final TableField<MemberRecord, Date> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>DB_VY_CORE.member.is_deleted</code>.
     */
    public final TableField<MemberRecord, Boolean> IS_DELETED = createField("is_deleted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>DB_VY_CORE.member</code> table reference
     */
    public Member() {
        this("member", null);
    }

    /**
     * Create an aliased <code>DB_VY_CORE.member</code> table reference
     */
    public Member(String alias) {
        this(alias, MEMBER);
    }

    private Member(String alias, Table<MemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private Member(String alias, Table<MemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbVyCore.DB_VY_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MemberRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MEMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MemberRecord> getPrimaryKey() {
        return Keys.KEY_MEMBER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MemberRecord>> getKeys() {
        return Arrays.<UniqueKey<MemberRecord>>asList(Keys.KEY_MEMBER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Member as(String alias) {
        return new Member(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Member rename(String name) {
        return new Member(name, null);
    }
}
